global:
  amf:
    service:
      ngap:
        enabled: true
        name: open5gs-amf-ngap
        port: 38412
        nodeport: 31412
        protocol: SCTP
        type: NodePort
  n2network:
    enabled: false






